"""
config.py — Central configuration for the South Holland 3-30-300 viewshed pipeline.

Edit the values in this file before running any script — except for the
machine-specific settings just below, which you override in a local
`config_local.py` (gitignored, never committed) instead. See
config_local.example.py for a template.
"""

import csv
import datetime
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR             = Path(__file__).parent.parent
DATA_DIR             = BASE_DIR / "data"
RAW_DIR              = DATA_DIR / "raw"          # source data, never written to by the pipeline
INTERIM_DIR          = DATA_DIR / "interim"      # tiled / intermediate artefacts
PROCESSED_DIR        = DATA_DIR / "processed"    # final merged output

DEM_TILES_DIR        = INTERIM_DIR / "dem_tiles"       # per municipality, generated by 01_tile_dem.py
VIEWSHED_TILES_DIR   = INTERIM_DIR / "viewshed_tiles"  # per municipality, per-tile results

# ---------------------------------------------------------------------------
# Machine-specific settings — placeholders below are safe to publish.
# Override them per machine in config_local.py (gitignored). Do not put real
# paths here; they'll end up in git history.
# ---------------------------------------------------------------------------

# Root of the QGIS / OSGeo4W install that holds GDAL/OGR (nothing is pip-installed).
OSGEO4W_ROOT = r"C:\OSGeo4W"

# Source: one DEM (.tif) + one tree-position layer (.gpkg) per municipality,
# sharing the same basename (e.g. Papendrecht.tif / Papendrecht.gpkg).
VIEWANALYSE_DIR = Path(r"\\your-server\path\to\viewanalyse")

# Restrict processing to these municipalities (by file basename).
# Empty list = process every tif/gpkg pair found in VIEWANALYSE_DIR.
MUNICIPALITIES = ["Papendrecht"]

# Municipalities to always skip regardless of MUNICIPALITIES above — e.g. a
# source DEM confirmed corrupted/empty. Override in config_local.py.
CORRUPTED_DEM_MUNICIPALITIES = []

# The province, exactly as named in PDOK's bestuurlijke gebieden (provincies.gpkg,
# field "naam"). Stage 5 keeps the buildings inside it; the output files are
# named after it (PROVINCE_SLUG, e.g. ZuidHolland_woningen.gpkg). To run another
# province, set this in config_local.py — see README "Another province".
PROVINCE = "Zuid-Holland"

# Where the FME results of the 30 and the 300 live (30_regel_v2.gdb, 300.gdb),
# read by web/build_tiles_30_300.py. Placeholder; set it in config_local.py.
FME_OUTPUT_DIR = Path(r"\\your-server\path\to\3-30-300\fme output")

try:
    from config_local import *  # noqa: F401,F403 — machine-specific overrides
except ImportError:
    pass

PROVINCE_SLUG = "".join(ch for ch in PROVINCE.title() if ch.isalnum())   # "ZuidHolland"

# Scripted per-municipality runs (see etl/run_all_municipalities.sh) set
# this to process exactly one municipality per invocation, overriding
# whatever MUNICIPALITIES is set to above.
_single = os.environ.get("MUNICIPALITY_OVERRIDE")
if _single:
    MUNICIPALITIES = [_single]


def municipality_pairs():
    """Yield (name, dem_path, trees_path) for every tif+gpkg pair in VIEWANALYSE_DIR,
    filtered by MUNICIPALITIES when that list is non-empty, and always
    excluding CORRUPTED_DEM_MUNICIPALITIES.

    Trees are read from a GeoPackage (converted once from the original .shp —
    GeoPackage has a built-in R-tree spatial index, unlike a bare shapefile,
    which made per-tile bbox queries scan the whole file and dominated
    runtime on larger municipalities)."""
    wanted = set(MUNICIPALITIES) if MUNICIPALITIES else None
    excluded = set(CORRUPTED_DEM_MUNICIPALITIES)
    for tif in sorted(VIEWANALYSE_DIR.glob("*.tif")):
        name = tif.stem
        if wanted is not None and name not in wanted:
            continue
        if name in excluded:
            continue
        gpkg = VIEWANALYSE_DIR / f"{name}.gpkg"
        if gpkg.exists():
            yield name, tif, gpkg


def require_municipality_pairs() -> list:
    """municipality_pairs() as a list; exits with a hint if there are none."""
    pairs = list(municipality_pairs())
    if not pairs:
        sys.exit(
            f"ERROR: no tif+gpkg pairs found in {VIEWANALYSE_DIR}\n"
            "Check config.VIEWANALYSE_DIR and config.MUNICIPALITIES."
        )
    return pairs


def dem_tiles_dir(name: str) -> Path:
    return DEM_TILES_DIR / name


def tile_index_path(name: str) -> Path:
    return dem_tiles_dir(name) / "tile_index.json"


def viewshed_tiles_dir(name: str) -> Path:
    return VIEWSHED_TILES_DIR / name


def final_output_path(name: str) -> Path:
    return PROCESSED_DIR / f"{name}_viewshed.tif"


# ---------------------------------------------------------------------------
# Cross-municipality context
# ---------------------------------------------------------------------------
# A tree or terrain feature just across a municipality boundary can still be
# within MAX_DISTANCE of a pixel on this side of it — the same seam problem
# already solved between tiles within one municipality, now at province
# scale. These combined sources let a tile near a municipality's edge pull
# real DEM/tree context from the neighbour instead of hitting a hard edge.
# Built once with:
#   gdalbuildvrt data/interim/province_dem.vrt <VIEWANALYSE_DIR>/*.tif
#   ogrmerge.py -o data/interim/province_trees.gpkg -single -nln province_trees \
#       -field_strategy Union -src_layer_field_name source_municipality \
#       -f GPKG -overwrite_ds <VIEWANALYSE_DIR>/*.gpkg
# TILE_BUFFER_PX (35m, below) already exceeds the required 30m, so the same
# buffer constant covers both the intra-municipality and cross-municipality
# halo — no separate constant needed.
PROVINCE_DEM_VRT    = INTERIM_DIR / "province_dem.vrt"
PROVINCE_TREES_GPKG = INTERIM_DIR / "province_trees.gpkg"

# ---------------------------------------------------------------------------
# Per-tree height
# ---------------------------------------------------------------------------
# Each tree's observer is placed at its canopy top: the max surface value
# within this radius of the tree point, ignoring building pixels (a roof edge
# next to a tree is not its crown).
TREE_HEIGHT_BUFFER_RADIUS = 1.5   # metres

# Own-crown removal (optional, 0 = off): before a tree's viewshed, every
# non-building DEM pixel within this radius of the tree is lowered to the
# local ground estimate, so its own crown can't block its own lines of sight.
# Building pixels (PROVINCE_BUILDINGS_GPKG, required when > 0) are never
# flattened. Off by default: on Delft, r=3 m changes the pass/fail (>=3
# trees) of only 0.1% of residential buildings vs the plain canopy top, at
# ~14% extra runtime — see ARCHITECTURE.md §6. The canopy-top observer
# already avoids nearly all self-occlusion.
OWN_CROWN_RADIUS = 0.0            # metres
# Residential building scores (04_score_buildings.py). A building counts as
# residential if at least one of its addresses (BAG verblijfsobjecten) in use
# has "woonfunctie" among its uses — so homes above shops are included.
# Its score is the max viewshed value in a ring of FACADE_RING_M around its
# facade (outside all footprints): there the 1.8 m target height is eye
# height above street/garden level, whereas inside a footprint the surface
# model is the roof, i.e. 1.8 m above the roof.
PROVINCE_ADDRESSES_GPKG = Path(os.environ.get(
    "ADDRESSES_GPKG_OVERRIDE", INTERIM_DIR / "province_addresses.gpkg"))  # env var: tests only
FACADE_RING_M = 1.5               # metres
# BAG field names (PDOK WFS / BAG GeoPackage naming; adjust for an SDE export)
BAG_BUILDING_ID = "identificatie"          # on the building footprints
BAG_ADDRESS_USE = "gebruiksdoel"           # on the addresses, comma-separated uses
BAG_ADDRESS_STATUS = "status"              # e.g. "Verblijfsobject in gebruik"
BAG_ADDRESS_BUILDING_ID = "pandidentificatie"  # building id(s) of the address
# Address statuses that count as "lived in". Excluded on purpose:
# "Verblijfsobject gevormd" (registered, not yet built/occupied — new builds,
# often not in the AHN surface model either) and "Verblijfsobject buiten
# gebruik"; also never-realised / withdrawn / wrongly registered objects.
BAG_STATUSES_IN_USE = (
    "verblijfsobject in gebruik",
    "verblijfsobject in gebruik (niet ingemeten)",
    "verbouwing verblijfsobject",   # under renovation: the homes still exist
)

# BAG building footprints (pand), province-wide: used by 04_score_buildings.py
# and, when OWN_CROWN_RADIUS > 0, by 02_compute_viewsheds.py.
PROVINCE_BUILDINGS_GPKG = Path(os.environ.get(
    "BUILDINGS_GPKG_OVERRIDE", INTERIM_DIR / "province_buildings.gpkg"))  # env var: tests only

# Local ground estimate for the plausibility check below: the lowest surface
# value within this radius of the tree. Only used to judge whether a sampled
# point is a plausible tree, never as the observer height.
TREE_GROUND_SEARCH_RADIUS = 5.0   # metres

# Sanity clamp, on height above local ground (not absolute NAP — South
# Holland ranges from ~-6 m in polders to ~+40 m in dunes). AHN's surface
# raster carries no point classification (see README) — there is no way to
# tell a power line, pylon, or building corner apart from a tree canopy in
# the raw elevation values. Dutch trees essentially never exceed this
# height; a sample above it almost certainly means the buffer caught
# something else, so fall back to OBSERVER_HEIGHT instead of trusting it.
TREE_HEIGHT_MAX_PLAUSIBLE = 35.0  # metres


# ---------------------------------------------------------------------------
# Benchmark logging — one row per (municipality, stage) run, appended as it
# happens so partial data survives if a long multi-municipality run is
# interrupted. See etl/generate_benchmark_report.py for turning this
# into BENCHMARKS.md.
# ---------------------------------------------------------------------------
BENCHMARK_LOG = BASE_DIR / "logs" / "benchmark.csv"
_BENCHMARK_FIELDS = ["timestamp", "municipality", "stage", "seconds", "tiles", "trees", "errors"]


def log_benchmark(municipality: str, stage: str, seconds: float, **extra) -> None:
    BENCHMARK_LOG.parent.mkdir(parents=True, exist_ok=True)
    is_new = not BENCHMARK_LOG.exists()
    with open(BENCHMARK_LOG, "a", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=_BENCHMARK_FIELDS)
        if is_new:
            writer.writeheader()
        writer.writerow({
            "timestamp": datetime.datetime.now().isoformat(timespec="seconds"),
            "municipality": municipality,
            "stage": stage,
            "seconds": f"{seconds:.1f}",
            "tiles": extra.get("tiles", ""),
            "trees": extra.get("trees", ""),
            "errors": extra.get("errors", ""),
        })


# ---------------------------------------------------------------------------
# OSGeo4W / GDAL
# ---------------------------------------------------------------------------
GDAL_BIN     = os.path.join(OSGEO4W_ROOT, "bin")
GDAL_DATA    = os.path.join(OSGEO4W_ROOT, "share", "gdal")
PROJ_LIB     = os.path.join(OSGEO4W_ROOT, "share", "proj")

# Inject so that osgeo imports work from any Python environment
os.environ.setdefault("GDAL_DATA", GDAL_DATA)
os.environ.setdefault("PROJ_LIB",  PROJ_LIB)
if GDAL_BIN not in os.environ.get("PATH", ""):
    os.environ["PATH"] = GDAL_BIN + os.pathsep + os.environ.get("PATH", "")

# Try adding OSGeo4W's own Python site-packages so 'from osgeo import gdal' works
_osgeo_pydir = os.path.join(OSGEO4W_ROOT, "apps", "Python312", "Lib", "site-packages")
if os.path.isdir(_osgeo_pydir) and _osgeo_pydir not in sys.path:
    sys.path.insert(0, _osgeo_pydir)

# ---------------------------------------------------------------------------
# Viewshed parameters — matches the original QGIS "3" (trees-visible) analysis
# ---------------------------------------------------------------------------
MAX_DISTANCE      = 30.0   # metres — radius of each individual viewshed
OBSERVER_HEIGHT   = 1.7    # metres above DEM surface (default when no height column)
# Every evaluated ground cell is raised by this much before the line-of-sight
# test — simulates eye/window height rather than testing visibility strictly
# at ground level. Matches the reference ArcGIS Pro methodology's
# surface_offset=1.8.
TARGET_HEIGHT     = 1.8    # metres above DEM surface for target pixels
CURVATURE_COEFF   = 0.0    # 0 = flat-earth; 0.85 = standard atmospheric refraction

# ---------------------------------------------------------------------------
# Tree layer settings
# ---------------------------------------------------------------------------
# Layer name inside the GeoPackage.  None = first layer auto-detected.
TREES_LAYER        = None

# ---------------------------------------------------------------------------
# DEM tiling  (01_tile_dem.py)
# ---------------------------------------------------------------------------
# Size of each inner tile in pixels.  At 0.5 m DEM resolution, 1000 px = 500 m.
TILE_PIXELS    = 1000

# Buffer added on all four sides (pixels).
# Must satisfy: TILE_BUFFER_PX * pixel_size >= MAX_DISTANCE
# At 0.5 m resolution: 70 px * 0.5 m = 35 m  ✓
# This buffer is a "halo": trees within it are read for context so that inner
# pixels near a tile edge get correct contributions from a neighbour's trees,
# but only the inner window is ever written to output (02_compute_viewsheds.py
# crops to it) — this is what prevents seam artefacts at tile boundaries.
TILE_BUFFER_PX = 70

# GeoTIFF creation options for tiled output
# DEFLATE + floating-point predictor: lossless, 2.3x smaller than LZW on a
# Delft tile (LZW without a predictor made Float32 tiles *bigger* than raw)
TILE_CREATION_OPTIONS = ["COMPRESS=DEFLATE", "PREDICTOR=3", "TILED=YES", "BIGTIFF=IF_SAFER"]

# ---------------------------------------------------------------------------
# Processing
# ---------------------------------------------------------------------------
NUM_WORKERS  = 4     # parallel processes for tile-level parallelism
LOG_EVERY    = 5000  # log a progress line every N trees within a tile
